### ISSUE TITLE
v1 TODO

### ISSUE THREAD

**Issue by rollomeister** [rollomeister/amari#1]
# Amari koduleht

Kodulehe esimene versioon

## Esileht
- [x] Lisa esilehele 2 linki marko meilist

## Navbar
- [x] Lisada venekeelne .pdf fail RUS lingi alla

## Footer
- [x] Copyright juriidika

## Roostevabad tooted
- [x] Mõõtudelt eemaldada reavahe
- [x] 1.4547/5040254 -> 1.4547/254SMO vms
- [x] Margid/Paksused/Mõõdud panna boldi
- [x] Plaadid columni laiused üle vaadata

## Outokumpu tooted
- [x] Muuta lingi aadress ära

## Alumiinium leht
- [x] Margid/Paksused/Mõõdud boldi
- [x] Erinevad profiilitüübid laiema reavahega üksteisest eraldada
- [x] Columni laiused korda

## Kontakt leht
- [x] Laotöölised -> Ladu
- [x] Müügiosakonna töötajate järjekorda muuta
- [x] Ken Saan -> Ken Karu

## Failid
- [x] Kustuta ebavajalikud failid

## Ettevõttest
- [x] Lisada Amari hoone pilt
