### ISSUE TITLE
1. Launch TODO

### ISSUE THREAD

**Issue by rollomeister** [rollomeister/amari#2]
# Amari koduleht

## HTML
- [ ] Igale .html failile lisada meta tagide sisse lehe märksõnad
- [ ] Google Analytics tag
- [ ] Vaadata kood HTMLlint-ga üle (vt. Bootlint bookmark)
- [ ] Lisada JS ja CSS CDN-id

## CSS
- [ ] HTML koodist kopeerida style tagide sisu CSS-i

## Navbar
- [ ] Hetke asukoha lingi peale ei 
- [ ] Bannerist mööda scrollides ilmub navbari Amari logo
- [x] Search bar eemaldada kuni pole funktsionaalsust
- [x] Navbar ühe rea peal
- [x] Lingid asuvad keskel (fill and justify)

## Otsing
- [ ] Funktsionaalsus (uuri CGI search scripte)
või
- [ ] Custom Google Search 
- [ ] Otsinguriba asukoht navbari paremas servas

## Footer
- [x] Kontakti vormi sisu max-height
- [x] Resize response
- [x] Scalable map
- [x] Üldkontakti kujundus
- [x] Autori copyright

### 1. artikkel
- [ ] Hea pilt otsida

### 2. artikkel
- [ ] Responsive disain
- [ ] Hea kujundus mõelda
- [ ] Pilte otsida

## Roostevaba leht
- [x] Alamlingid
- [ ] Sisu
- [ ] Hetke asukoha kirjeldus

## Alumiinium leht
- [ ] Sisu

## Ettevõtte leht
- [ ] Sisu

## Kontakt leht
- [ ] Sisu
- [ ] Osakonnad

## Failid
- [ ] Kustuta ebavajalikud failid
- [ ] Klikitavad pildid

### Turvalisus
- [ ] Inputi spammi kaitse
- [ ]
